### ISSUE TITLE
Palworld config files dont update

### ISSUE THREAD

**Issue by jameswilsonacre** [KagurazakaNyaa/palworld-docker#13]
Hey,

It seems like at the moment the bash script doesnt handle updating config very well (in that it's only set once).

Even if under a flag can we force a config rewrite on start without having to remote into the container and deleting the config?

**Comment by KagurazakaNyaa** [comment]
I do not recommend using this method to implement re-initialization, because the configuration file of this game not only contains initialization content through environment variables, but also has many configurations that require manual adjustment by the user. If the container uses an environment variable to force it to start If the configuration file is reinitialized, these modifications will be lost.
