### ISSUE TITLE
docker-entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by larrydemons** [KagurazakaNyaa/palworld-docker#2]
lighthouse@VM-0-7-ubuntu:~/palworld-docker$ sudo docker logs 731935c1404c
/bin/bash: /docker-entrypoint.sh: Permission denied
/bin/bash: /docker-entrypoint.sh: Permission denied
/bin/bash: /docker-entrypoint.sh: Permission denied
/bin/bash: /docker-entrypoint.sh: Permission denied
/bin/bash: /docker-entrypoint.sh: Permission denied
/bin/bash: /docker-entrypoint.sh: Permission denied
/bin/bash: /docker-entrypoint.sh: Permission denied
/bin/bash: /docker-entrypoint.sh: Permission denied

**Comment by KagurazakaNyaa** [comment]
It seems that the permissions of `docker-entrypoint.sh` were not handled properly when building the image yourself. You can try to pull the image directly, or retry the build after executing `chmod +x docker-entrypoint.sh`.
At the same time, you can check whether the permissions are incorrect due to problems caused by git clone. Please refer to https://stackoverflow.com/a/4408378

**Comment by KagurazakaNyaa** [comment]
If this problem is solved, I will close this issue. If you still encounter this problem, you are welcome to reopen it.
